//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bShop.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        public static string Affiliate {
            get {
                return ResourceManager.GetString("Affiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Category.
        /// </summary>
        public static string AllCategory {
            get {
                return ResourceManager.GetString("AllCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Language.
        /// </summary>
        public static string AllLanguage {
            get {
                return ResourceManager.GetString("AllLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved by.
        /// </summary>
        public static string AllRightsReservedBy {
            get {
                return ResourceManager.GetString("AllRightsReservedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrivals.
        /// </summary>
        public static string Arrivals {
            get {
                return ResourceManager.GetString("Arrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Offer.
        /// </summary>
        public static string AvailableOffer {
            get {
                return ResourceManager.GetString("AvailableOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sellers.
        /// </summary>
        public static string BestSellers {
            get {
                return ResourceManager.GetString("BestSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bShop Street, Our City.
        /// </summary>
        public static string BShop_Address {
            get {
                return ResourceManager.GetString("BShop_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@bshop.com.
        /// </summary>
        public static string BShop_Email {
            get {
                return ResourceManager.GetString("BShop_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://facebook.com/bshop.
        /// </summary>
        public static string BShop_FacebookLink {
            get {
                return ResourceManager.GetString("BShop_FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://instagram.com/bshop.
        /// </summary>
        public static string BShop_InstagramLink {
            get {
                return ResourceManager.GetString("BShop_InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 964 123 456789.
        /// </summary>
        public static string BShop_PhoneNumber {
            get {
                return ResourceManager.GetString("BShop_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/bshop.
        /// </summary>
        public static string BShop_TwitterLink {
            get {
                return ResourceManager.GetString("BShop_TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtube.com/bshop.
        /// </summary>
        public static string BShop_YoutubeLink {
            get {
                return ResourceManager.GetString("BShop_YoutubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to server..
        /// </summary>
        public static string CantConnectToServer {
            get {
                return ResourceManager.GetString("CantConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Password....
        /// </summary>
        public static string ChangingPassword {
            get {
                return ResourceManager.GetString("ChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Policy.
        /// </summary>
        public static string CookiePolicy {
            get {
                return ResourceManager.GetString("CookiePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an customer account.
        /// </summary>
        public static string CreateAnCustomerAccount {
            get {
                return ResourceManager.GetString("CreateAnCustomerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new migration to update database:&lt;br/&gt;&lt;ul&gt;{0}&lt;/ul&gt;.
        /// </summary>
        public static string CreateNewMigrationToUpdateDatabase {
            get {
                return ResourceManager.GetString("CreateNewMigrationToUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You email confirmed successfully! Now you can login..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old password and new one to change your password.
        /// </summary>
        public static string EnterOldPasswordAndNewOneToChangeYourPassword {
            get {
                return ResourceManager.GetString("EnterOldPasswordAndNewOneToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string EnterYourEmailAddress {
            get {
                return ResourceManager.GetString("EnterYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address below and we will send you a link to reset your password.
        /// </summary>
        public static string EnterYourEmailAddressBelowAndWeWillSendYouALinkToResetYourPassword {
            get {
                return ResourceManager.GetString("EnterYourEmailAddressBelowAndWeWillSendYouALinkToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        public static string EnterYourNewPassword {
            get {
                return ResourceManager.GetString("EnterYourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to database..
        /// </summary>
        public static string Error_CantConnectToDatabase {
            get {
                return ResourceManager.GetString("Error_CantConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mapping type: {0}.
        /// </summary>
        public static string Error_MissingMappingType {
            get {
                return ResourceManager.GetString("Error_MissingMappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Connection string &apos;{0}&apos; in &apos;appsettings.json&apos; file..
        /// </summary>
        public static string ExceptionConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ExceptionConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Jwt:Key in appsettings.json file..
        /// </summary>
        public static string ExceptionJwtKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionJwtKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCAPTCHA SecretKey Is Null.
        /// </summary>
        public static string ExceptionReCAPTCHASecretKeyIsNull {
            get {
                return ResourceManager.GetString("ExceptionReCAPTCHASecretKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCAPTCHA SiteKey Is Null.
        /// </summary>
        public static string ExceptionReCAPTCHASiteKeyIsNull {
            get {
                return ResourceManager.GetString("ExceptionReCAPTCHASiteKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Brand.
        /// </summary>
        public static string FilterByBrand {
            get {
                return ResourceManager.GetString("FilterByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Category.
        /// </summary>
        public static string FilterByCategory {
            get {
                return ResourceManager.GetString("FilterByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Home.
        /// </summary>
        public static string GoBackToHome {
            get {
                return ResourceManager.GetString("GoBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link is not valid..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loging in....
        /// </summary>
        public static string LogingIn {
            get {
                return ResourceManager.GetString("LogingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: A-Z.
        /// </summary>
        public static string NameAZ {
            get {
                return ResourceManager.GetString("NameAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Z-A.
        /// </summary>
        public static string NameZA {
            get {
                return ResourceManager.GetString("NameZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        public static string NewArrivals {
            get {
                return ResourceManager.GetString("NewArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no languages added yet..
        /// </summary>
        public static string NoLanguageAddedYet {
            get {
                return ResourceManager.GetString("NoLanguageAddedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Offer.
        /// </summary>
        public static string OfferBy {
            get {
                return ResourceManager.GetString("OfferBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! No product found..
        /// </summary>
        public static string OopsNoProductFound {
            get {
                return ResourceManager.GetString("OopsNoProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The page you&apos;re looking for is not here..
        /// </summary>
        public static string OopsThePageYoureLookingForIsNotHere {
            get {
                return ResourceManager.GetString("OopsThePageYoureLookingForIsNotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order#.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Tracking.
        /// </summary>
        public static string OrderTracking {
            get {
                return ResourceManager.GetString("OrderTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password changed successfully..
        /// </summary>
        public static string PasswordChangedSucceeded {
            get {
                return ResourceManager.GetString("PasswordChangedSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a digit..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a lowercase letter..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a non-alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires an uppercase letter..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password resetted successfully! Now you can login using the new password..
        /// </summary>
        public static string PasswordReseted {
            get {
                return ResourceManager.GetString("PasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is too short..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address....
        /// </summary>
        public static string PlaceHolder_Address {
            get {
                return ResourceManager.GetString("PlaceHolder_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password again....
        /// </summary>
        public static string PlaceHolder_ConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceHolder_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address....
        /// </summary>
        public static string PlaceHolder_Email {
            get {
                return ResourceManager.GetString("PlaceHolder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name....
        /// </summary>
        public static string PlaceHolder_FirstName {
            get {
                return ResourceManager.GetString("PlaceHolder_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name....
        /// </summary>
        public static string PlaceHolder_LastName {
            get {
                return ResourceManager.GetString("PlaceHolder_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password....
        /// </summary>
        public static string PlaceHolder_NewPassword {
            get {
                return ResourceManager.GetString("PlaceHolder_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password....
        /// </summary>
        public static string PlaceHolder_OldPassword {
            get {
                return ResourceManager.GetString("PlaceHolder_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string PlaceHolder_Password {
            get {
                return ResourceManager.GetString("PlaceHolder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number....
        /// </summary>
        public static string PlaceHolder_PhonNumber {
            get {
                return ResourceManager.GetString("PlaceHolder_PhonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Products....
        /// </summary>
        public static string PlaceHolder_SearchForProducts {
            get {
                return ResourceManager.GetString("PlaceHolder_SearchForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address and password.
        /// </summary>
        public static string PleaseEnterYourEmailAddressAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourEmailAddressAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the information below.
        /// </summary>
        public static string PleaseFillInTheInformationBelow {
            get {
                return ResourceManager.GetString("PleaseFillInTheInformationBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string ProductsList {
            get {
                return ResourceManager.GetString("ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Policy.
        /// </summary>
        public static string PurchasingPolicy {
            get {
                return ResourceManager.GetString("PurchasingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering....
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sign in session is finshed and you need to resign in again..
        /// </summary>
        public static string ResigninAgain {
            get {
                return ResourceManager.GetString("ResigninAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL.
        /// </summary>
        public static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoCode.
        /// </summary>
        public static string SeoCode {
            get {
                return ResourceManager.GetString("SeoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +90 (567) 890 1234.
        /// </summary>
        public static string Shop_PhoneNumber {
            get {
                return ResourceManager.GetString("Shop_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop by Brands.
        /// </summary>
        public static string ShopByBrands {
            get {
                return ResourceManager.GetString("ShopByBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Now.
        /// </summary>
        public static string ShopNow {
            get {
                return ResourceManager.GetString("ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for an account?.
        /// </summary>
        public static string SignUpForAnAccount {
            get {
                return ResourceManager.GetString("SignUpForAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold By.
        /// </summary>
        public static string SoldBy {
            get {
                return ResourceManager.GetString("SoldBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password requires a unique character..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add email to our list.
        /// </summary>
        public static string SubscribeFailed {
            get {
                return ResourceManager.GetString("SubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe our newsletter.
        /// </summary>
        public static string SubscribeOurNewsletter {
            get {
                return ResourceManager.GetString("SubscribeOurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is added to our list.
        /// </summary>
        public static string SubscribeSuccess {
            get {
                return ResourceManager.GetString("SubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the mailing list to receive updates on special offers, new arrivals and our promotions..
        /// </summary>
        public static string SubscribeToTheMailingListToReceiveUpdatesOnSpecialOffersNewArrivalsAndOurPromotions {
            get {
                return ResourceManager.GetString("SubscribeToTheMailingListToReceiveUpdatesOnSpecialOffersNewArrivalsAndOurPromotio" +
                        "ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Categories.
        /// </summary>
        public static string TopCategories {
            get {
                return ResourceManager.GetString("TopCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking your order status.
        /// </summary>
        public static string TrackingYourOrderStatus {
            get {
                return ResourceManager.GetString("TrackingYourOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consectetur adipisicing elit. Dolores nisi distinctio magni.
        /// </summary>
        public static string TrendingDescription {
            get {
                return ResourceManager.GetString("TrendingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Products.
        /// </summary>
        public static string TrendingProducts {
            get {
                return ResourceManager.GetString("TrendingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile updated successfully..
        /// </summary>
        public static string UpdatingProfileSucceeded {
            get {
                return ResourceManager.GetString("UpdatingProfileSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password changed successfully! Now you can login using the new password..
        /// </summary>
        public static string UserChangePasswordSucceeded {
            get {
                return ResourceManager.GetString("UserChangePasswordSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email used before..
        /// </summary>
        public static string UserEmailAddedBefore {
            get {
                return ResourceManager.GetString("UserEmailAddedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked..
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login.
        /// </summary>
        public static string UserLoginFailed {
            get {
                return ResourceManager.GetString("UserLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded loged in.
        /// </summary>
        public static string UserLoginSucceeded {
            get {
                return ResourceManager.GetString("UserLoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded loged out.
        /// </summary>
        public static string UserLogoutSucceeded {
            get {
                return ResourceManager.GetString("UserLogoutSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email in not confirmed yet..
        /// </summary>
        public static string UserNeedEmailActivation {
            get {
                return ResourceManager.GetString("UserNeedEmailActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active..
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded password resetted..
        /// </summary>
        public static string UserResetPasswordSucceeded {
            get {
                return ResourceManager.GetString("UserResetPasswordSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset link sent to your email..
        /// </summary>
        public static string UserResetSucceeded {
            get {
                return ResourceManager.GetString("UserResetSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is added before..
        /// </summary>
        public static string Validation_Unique {
            get {
                return ResourceManager.GetString("Validation_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
    }
}
